// The sitemap (#158). The directory gave every work a URL; this is what tells anybody
// those URLs exist.
//
// Split one file per letter with `generateSitemaps`, which is not a performance nicety:
// the protocol caps a sitemap at 50,000 URLs and 50 MB, and while 6,392 works fit inside
// one today, a per-letter split keeps each file small enough to regenerate cheaply and
// survives the catalogue growing without anyone noticing the limit.
//
// Every URL here is generated by the same `workPath` and `cityPath` the pages parse, so a
// sitemap entry cannot point somewhere the app would 404 — the failure mode of a
// hand-written sitemap.

import { GET as filmsRoute } from "./api/directory/films/route.js";
import { ALL_CITIES, cityPath } from "./lib/city-gazetteer.mjs";
import { DIRECTORY_LETTERS, letterToSlug } from "./lib/directory.mjs";
import { workPath } from "./lib/work-url.mjs";

// A sitemap must carry absolute URLs. Vercel exposes the deployment host but not the
// canonical one, so the production domain is the default and an override exists for
// anybody serving this somewhere else.
const SITE =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/+$/, "") ||
  "https://codex-hackathon-starter.vercel.app";

// 500 is the function's own ceiling; the largest letter held 640 works on 18.08, so a
// letter needs two passes at most today and the loop is written to take as many as it needs.
const PAGE_SIZE = 500;

export function generateSitemaps() {
  return DIRECTORY_LETTERS.map((letter) => ({ id: letterToSlug(letter) }));
}

async function worksForLetter(slug) {
  const works = [];
  for (let page = 1; ; page += 1) {
    const url = new URL("https://glorymap.local/api/directory/films");
    url.searchParams.set("letter", slug);
    url.searchParams.set("page", String(page));
    const response = await filmsRoute(new Request(url));
    if (!response.ok) break;
    const data = await response.json();
    works.push(...(data.works ?? []));
    if (!data.page?.hasNext) break;
  }
  return works;
}

export default async function sitemap({ id }) {
  const slug = String(id ?? "a");

  // The pages that are not works ride on the first file rather than getting one of their
  // own: they are 84 URLs, and a sitemap index of 28 files where one holds 84 entries and
  // another holds 3 is harder to read than one where the first is slightly larger.
  const fixed =
    slug === "a"
      ? [
          { url: `${SITE}/`, changeFrequency: "daily", priority: 1 },
          { url: `${SITE}/directory`, changeFrequency: "weekly", priority: 0.8 },
          ...DIRECTORY_LETTERS.map((letter) => ({
            url: `${SITE}/directory/films/${letterToSlug(letter)}`,
            changeFrequency: "weekly",
            priority: 0.5,
          })),
          ...ALL_CITIES.map((city) => ({
            url: `${SITE}${cityPath(city)}`,
            changeFrequency: "weekly",
            priority: 0.7,
          })),
        ]
      : [];

  let works = [];
  try {
    works = await worksForLetter(slug);
  } catch {
    // A sitemap that throws is a build that fails. An incomplete sitemap costs a crawl;
    // a broken one costs the deploy, and the fixed URLs above are still worth serving.
    works = [];
  }

  return [
    ...fixed,
    ...works
      .map((work) => workPath(work))
      .filter(Boolean)
      .map((path) => ({ url: `${SITE}${path}`, changeFrequency: "monthly", priority: 0.6 })),
  ];
}
