// The sitemap (#158). The directory gave every work a URL; this is what tells anybody
// those URLs exist.
//
// Split one file per letter with `generateSitemaps`, which is not a performance nicety:
// the protocol caps a sitemap at 50,000 URLs and 50 MB, and while 6,392 works fit inside
// one today, a per-letter split keeps each file small enough to regenerate cheaply and
// survives the catalogue growing without anyone noticing the limit.
//
// Every URL here is generated by the same `workPath`, `cityPath` and `placePath` the pages
// parse, so a sitemap entry cannot point somewhere the app would 404 — the failure mode of
// a hand-written sitemap.

import { GET as filmsRoute } from "./api/directory/films/route.js";
import { GET as placesRoute } from "./api/directory/places/route.js";
import { ALL_CITIES, cityPath } from "./lib/city-gazetteer.mjs";
import { DIRECTORY_LETTERS, letterToSlug } from "./lib/directory.mjs";
import { placePath } from "./lib/place-url.mjs";
import { SITE_URL as SITE } from "./lib/site-url.mjs";
import { workPath } from "./lib/work-url.mjs";

// 500 is the function's own ceiling; the largest letter held 640 works on 18.08, so a
// letter needs two passes at most today and the loop is written to take as many as it needs.
const PAGE_SIZE = 500;

export function generateSitemaps() {
  return DIRECTORY_LETTERS.map((letter) => ({ id: letterToSlug(letter) }));
}

async function worksForLetter(slug) {
  const works = [];
  for (let page = 1; ; page += 1) {
    const url = new URL("https://glorymap.local/api/directory/films");
    url.searchParams.set("letter", slug);
    url.searchParams.set("page", String(page));
    const response = await filmsRoute(new Request(url));
    if (!response.ok) break;
    const data = await response.json();
    works.push(...(data.works ?? []));
    if (!data.page?.hasNext) break;
  }
  return works;
}

// The places, walked the same way as a letter of the catalogue. The route lists only the
// places a page can actually be built from, so what comes back is already the set of place
// URLs that resolve — see app/api/directory/places/route.js.
export async function placesInTheGraph(route = placesRoute) {
  const places = [];
  for (let page = 1; ; page += 1) {
    const url = new URL("https://glorymap.local/api/directory/places");
    url.searchParams.set("page", String(page));
    const response = await route(new Request(url));
    if (!response.ok) break;
    const data = await response.json();
    places.push(...(data.places ?? []));
    if (!data.page?.hasNext) break;
  }
  return places;
}

// The second argument is for the tests and Next never passes it: Next calls this with the
// params alone, and the property worth pinning — that a place URL is built by `placePath`
// and rides on the first file — cannot be seen without handing it places to build from.
export default async function sitemap({ id }, { loadPlaces = placesInTheGraph } = {}) {
  const slug = String(id ?? "a");

  // Asked for once, on the file that carries them. A place has no letter to be filed under
  // — its URL is a name and a uuid, not a title — so there is no per-letter split to make.
  let places = [];
  if (slug === "a") {
    try {
      places = await loadPlaces();
    } catch {
      // Same rule as the works below: an incomplete sitemap costs a crawl, a throw costs
      // the deploy.
      places = [];
    }
  }

  // The pages that are not works ride on the first file rather than getting one of their
  // own: they are 154 URLs — 84 fixed pages and the graph's 70 places, measured 10.09 — and
  // a sitemap index of 27 files where one holds 154 entries and another holds 3 is harder
  // to read than one where the first is slightly larger.
  const fixed =
    slug === "a"
      ? [
          { url: `${SITE}/`, changeFrequency: "daily", priority: 1 },
          { url: `${SITE}/directory`, changeFrequency: "weekly", priority: 0.8 },
          ...DIRECTORY_LETTERS.map((letter) => ({
            url: `${SITE}/directory/films/${letterToSlug(letter)}`,
            changeFrequency: "weekly",
            priority: 0.5,
          })),
          ...ALL_CITIES.map((city) => ({
            url: `${SITE}${cityPath(city)}`,
            changeFrequency: "weekly",
            priority: 0.7,
          })),
          // Same weight as a work: a place page is one of the two ends of the same table,
          // and 6 of the 70 are the only page in the app that shows what they show.
          ...places
            .map((place) => placePath(place))
            .filter(Boolean)
            .map((path) => ({ url: `${SITE}${path}`, changeFrequency: "monthly", priority: 0.6 })),
        ]
      : [];

  let works = [];
  try {
    works = await worksForLetter(slug);
  } catch {
    // A sitemap that throws is a build that fails. An incomplete sitemap costs a crawl;
    // a broken one costs the deploy, and the fixed URLs above are still worth serving.
    works = [];
  }

  return [
    ...fixed,
    ...works
      .map((work) => workPath(work))
      .filter(Boolean)
      .map((path) => ({ url: `${SITE}${path}`, changeFrequency: "monthly", priority: 0.6 })),
  ];
}
